<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proceed_B</name>
   <tag></tag>
   <elementGuidId>60b424fe-2db8-46bd-8380-00fbfbbeeacb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='proceed-link']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proceed-link</value>
      <webElementGuid>b46a66f5-35b4-44d3-b301-f94c43b90708</webElementGuid>
   </webElementProperties>
</WebElementEntity>
