<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>discoveryPage</name>
   <tag></tag>
   <elementGuidId>edfd8507-3d42-4d84-a836-cf67636583d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;admin-discovery&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
