<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Naviate_to_admintab</name>
   <tag></tag>
   <elementGuidId>643e60a9-c85e-4be8-9f47-b5754fb41962</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'AdminButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AdminButton</value>
      <webElementGuid>b2db7cbe-a43f-45b8-a067-da336971a6c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
