<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>statuscoulmn</name>
   <tag></tag>
   <elementGuidId>8ef597f6-09ae-446d-9a89-5482d0fae731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='${BSMname}']//parent::a//parent::span//parent::div//following-sibling::div//child::span[text()='Enabled']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
