<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contextMenu</name>
   <tag></tag>
   <elementGuidId>3f5bd997-5609-43f0-9968-d837190e0006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()=&quot;${host}&quot;]/parent::a/parent::span/parent::div//following-sibling::div//div[@class=&quot;context-menu&quot;]//span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
